services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: 'Mm002580!'
      MYSQL_ROOT_HOST: '%'
    ports:
      - '3306:3306'
    networks:
      - mynetwork
    command: --default-authentication-plugin=mysql_native_password

  redis:
    image: redis:6.2-alpine
    container_name: redis-container
    ports:
      - '6379:6379'
    networks:
      - mynetwork

networks:
  mynetwork:
