name: Package on Push

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - name: 创建 SSH 配置
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "StrictHostKeyChecking no" >> ~/.ssh/config
          echo "UserKnownHostsFile=/dev/null" >> ~/.ssh/config

      - name: 测试 SSH 连接
        run: |
          count=1
          for IP in ${{ secrets.SSH_SERVER_IP_DISCORD }} ${{ secrets.SSH_SERVER_IP_QQ_BOT }}; do
            echo "Testing SSH connection to IP $count..."
            ssh -o BatchMode=yes -o StrictHostKeyChecking=no ${{ secrets.SSH_SERVER_USER }}@$IP "echo 'SSH connection to $count successful!' || echo 'Connection failed for $count'"
            count=$((count + 1))
          done

      - name: 使用 Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: 检出工作区
        uses: actions/checkout@v2

      - name: 打包文件
        run: |
          sh .github/script/build.sh

      - name: 安装 rsync
        run: |
          sudo apt-get update 
          sudo apt-get install rsync -y
          rsync --version

      - name: 推送到 qq-bot 服务器
        run: |
          ssh ${{ secrets.SSH_SERVER_USER }}@${{ secrets.SSH_SERVER_IP_QQ_BOT }} "cd /home/lighthouse/qq-guild-bot && if [ -d node_modules ]; then npx pm2 kill ;fi &"  
          mkdir build
          echo "${{ secrets.SSH_ALEMON_CONFIG_QQBOT }}" > ./build/alemon.config.yaml
          rsync -avz --delete ./build/ ${{ secrets.SSH_SERVER_USER }}@${{ secrets.SSH_SERVER_IP_QQ_BOT }}:/home/lighthouse/qq-bot
          ssh ${{ secrets.SSH_SERVER_USER }}@${{ secrets.SSH_SERVER_IP_QQ_BOT }} "cd /home/lighthouse/qq-bot && yarn install && yarn start&"
        continue-on-error: true
