name: Package on Push

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 创建 SSH 配置
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "StrictHostKeyChecking no" >> ~/.ssh/config
          echo "UserKnownHostsFile=/dev/null" >> ~/.ssh/config

      - name: 测试 SSH 连接
        run: |
          for IP in ${{ secrets.SSH_SERVER_IP_CONFIG }} ${{ secrets.SSH_SERVER_IP_DISCORD }} ${{ secrets.SSH_SERVER_IP_QQ_BOT }}  ${{ secrets.SSH_SERVER_IP_QQ }}; do
            echo "Testing SSH connection to $IP..."
            ssh -o BatchMode=yes -o StrictHostKeyChecking=no ${{ secrets.SSH_SERVER_USER }}@$IP "echo 'SSH connection to $IP successful!' || echo 'Connection failed for $IP'"
          done

      - name: 安装 rsync
        run: |
          sudo apt-get update 
          sudo apt-get install -y rsync

      - name: 使用 Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: 检出工作区
        uses: actions/checkout@v2

      - name: 打包文件
        run: |
          sh .github/script/build.sh

      - name: 推送到 Discord 服务器
        run: |
          scp ${{ secrets.SSH_SERVER_USER }}@${{ secrets.SSH_SERVER_IP_CONFIG }}:/home/lighthouse/config/alemon.config.yaml alemon.config.yaml
          sh .github/script/discord.sh
          rsync -avz --delete ./build/ ${{ secrets.SSH_SERVER_USER }}@${{ secrets.SSH_SERVER_IP_DISCORD }}:/home/lighthouse/discord

      - name: 推送到 QQBOT 服务器
        run: |
          scp ${{ secrets.SSH_SERVER_USER }}@${{ secrets.SSH_SERVER_IP_CONFIG }}:/home/lighthouse/config/alemon.config.yaml alemon.config.yaml
          sh .github/script/qq-group-bot.sh
          rsync -avz --delete ./build/ ${{ secrets.SSH_SERVER_USER }}@${{ secrets.SSH_SERVER_IP_QQ_BOT }}:/home/lighthouse/qq-group-bot

      # - name: 推送到 QQ 服务器
      #   run: |
      #     scp ${{ secrets.SSH_SERVER_USER }}@${{ secrets.SSH_SERVER_IP_CONFIG }}:/home/lighthouse/config/alemon.config.yaml alemon.config.yaml
      #     sh .github/script/qq.sh
      #     rsync -avz --delete ./build/ ${{ secrets.SSH_SERVER_USER }}@${{ secrets.SSH_SERVER_IP_QQ }}:/home/lighthouse/qq
